export const ADD_PLACE = 'ADD_PLACE';
export const ADD_PLACE_SUCCESS = 'ADD_PLACE_SUCCESS';
export const DELETE_PLACE = 'DELETE_PLACE';
export const DELETE_PLACE_SUCCESS = 'DELETE_PLACE_SUCCESS';

export const TRY_LOGIN = 'TRY_LOGIN';
export const TRY_LOGIN_SUCCESS = 'TRY_LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SET_LOADING = 'SET_LOADING';
export const SET_LOADING_SUCCESS = 'SET_LOADING_SUCCESS';
export const SET_SELECTED_TAB = 'SET_SELECTED_TAB';
export const SET_SELECTED_TAB_SUCCESS = 'SET_SELECTED_TAB_SUCCESS';
